db.url=jdbc:mysql://127.0.0.1:3307/part_time_job?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
db.user=root
db.password=?

ssh.host=8.163.2.44
ssh.port=22
ssh.user=admin
ssh.password=?
ssh.localPort=3307
ssh.remoteHost=127.0.0.1
ssh.remotePort=3306
